name: deploy-prod
on:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GA_SSH_PRIVKEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.GA_SSH_PORT }} -H ${{ secrets.GA_SSH_IPADDRESS }} >> ~/.ssh/known_hosts

      - name: Run prod script
        run: ssh -p ${{ secrets.GA_SSH_PORT }} ${{ secrets.GA_SSH_USER }}@${{ secrets.GA_SSH_IPADDRESS }} "bash /home/Projects/SurgeToken/SurgeDevops/deploy_prod_web.sh"

      - name: cleanup docker
        run: ssh -p ${{ secrets.GA_SSH_PORT }} ${{ secrets.GA_SSH_USER }}@${{ secrets.GA_SSH_IPADDRESS }} "bash /home/Projects/SurgeToken/SurgeDevops/cleanup.sh"
